"""Initial Migration

Revision ID: 391357cbd8c4
Revises: df881501f97e
Create Date: 2022-08-28 23:03:00.059388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391357cbd8c4'
down_revision = 'df881501f97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('movie_review', sa.String(), nullable=True))
    op.drop_column('reviews', 'review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'movie_review')
    # ### end Alembic commands ###
